server:
  port: 9012
spring:
  application:
    name: epic-cp9
  datasource:
    url: "jdbc:mysql://47.101.177.31:3306/zmsj?useUnicode=true&characterEncoding=UTF-8"
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: mybatis/*.xml