server:
  port: 9012
spring:
  application:
    name: epic-cp9
  datasource:
    url: "jdbc:mysql://139.129.163.156:3306/zy_ecology?useUnicode=true&characterEncoding=UTF-8"
    username: ziyouxing
    password: ziyouxing
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: mybatis/*.xml